# Generated by Django 6.0.6 on 2026-06-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Sistema de Asistencias', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('color_principal', models.CharField(default='#1a3c6e', max_length=7)),
                ('color_secundario', models.CharField(default='#2a5298', max_length=7)),
                ('logo_sistema', models.ImageField(blank=True, null=True, upload_to='sistema/')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_iglesia', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Iglesia',
                'verbose_name_plural': 'Iglesias',
            },
        ),
        migrations.CreateModel(
            name='ModoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('mensaje', models.TextField(default='Estamos realizando actualizaciones. Por favor vuelve pronto.')),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modo mantenimiento',
                'verbose_name_plural': 'Modo mantenimiento',
            },
        ),
    ]
